ecommerce/cart/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, IntegerField, SelectField, PasswordField, SubmitField,
        BooleanField, TextAreaField, HiddenField)
from wtforms.validators import DataRequired, Length, Email, EqualTo

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class ItemAddToCart(FlaskForm):
    quantity = SelectField('quantity', coerce=int)
    submit = SubmitField('add')

class ClearCartForm(FlaskForm):
    clear = SubmitField("CLEAR CART")

class ChoosePaymentMethodForm(FlaskForm):
    payment_method = SelectField('payment method', coerce=int)
    submit = SubmitField('Order')

ecommerce/catalog/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, g, session
from ecommerce.catalog.forms import CategoryCreateForm, ProductCreateForm, ProductUpdateForm
from ecommerce.db import Database as db
#from ecommerce.users.routes import before_request as g
#from ecommerce import mysql

catalog = Blueprint('catalog', __name__)

@catalog.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

# Category list
@catalog.route('/categories')
def category_list():
    # retrieve all category object from database
    with db.connection.cursor() as cursor:
        cursor.execute('SELECT COUNT(name) AS product_count, name AS p_name, category_name FROM product_view GROUP BY category_name')
        category_list = cursor.fetchall()

    return render_template('category_list.html', category_list=category_list)

# Add product
@catalog.route('/store/<string:id>/products/new', methods=['GET', 'POST'])
def product_create(id):
    form = ProductCreateForm()
    
    with db.connection.cursor() as cursor:
        # reconnect by default because heroku server connection is unstable
        db.reconnect()
        
        # get this store_id
        #cursor.execute('SELECT * FROM user WHERE store_id=(%s)', (id))
        #user = cursor.fetchone()

        # select all categories
        cursor.execute('SELECT * FROM category')
        category_list = cursor.fetchall()
        form.category.choices = [(category['category_id'], category['category_name']) for category in category_list]

        if form.validate_on_submit():
            cursor.execute('''INSERT INTO product (name, price, available, category_id, description, store_id) VALUES (%s, %s, %s, %s, %s, %s)''', (
                                  form.name.data,
                                  form.price.data,
                                  True,
                                  form.category.data,
                                  form.description.data,
                                  g.user['store_id']))
            # Commit changes to db
            db.connection.commit()
            flash('Product added')
        
            return redirect(url_for('store.store_manager', id=g.user['store_id']))
 
    return render_template('product_create.html', form=form)

# Product details
@catalog.route('/product/<string:id>')
def product_detail(id):
    '''Retrieve one product by id'''
    
    with db.connection.cursor() as cursor:
        db.reconnect()
        # Retrieve product details with related data from category and store table
        cursor.execute('SELECT * FROM product p '
                       'INNER JOIN category c ON p.category_id=c.category_id ' 
                       'INNER JOIN store s ON p.store_id=s.store_id ' 
                       'WHERE p.product_id=(%s)', (id))
        product = cursor.fetchone()
        
        # retrieve products from this product's store
        #cursor.execute('SELECT p.name, p.price FROM product p '
        #               'INNER JOIN store s ON p.store_id=s.store_id '
        #               'WHERE s.store_id=p.store_id')
        

    return render_template('product_detail.html', product=product)

@catalog.route('/product/update/<string:id>', methods=['GET','POST'])
def product_update(id):
    '''Controller to update produc object'''
    form = ProductUpdateForm()
    
    with db.connection.cursor() as cursor:
        # reconnect to heroku cleardb database
        db.reconnect()
        # get this product
        cursor.execute('SELECT * FROM product WHERE product.product_id=(%s)', (id))
        product = cursor.fetchone()
        
        # Get the categories
        cursor.execute('SELECT * FROM category')
        category_list = cursor.fetchall()
        form.category.choices = [(category['category_id'], category['category_name']) for category in category_list]

        # populate fields with current data
        form.name.data = product['name']
        form.price.data = product['price']    
        form.category.data = product['category_id']
        form.description.data = product['description']

        if form.validate_on_submit():
            # insert the updated data into product
            cursor.execute('UPDATE product '
                       'SET name=(%s), price=(%s), category_id=(%s), description=(%s) '
                       'WHERE product_id=(%s)', (
                        request.form['name'],
                        request.form['price'],
                        request.form['category'],
                        request.form['description'],
                        id))
            # commit updates
            db.connection.commit()
            
            flash('{} has been updated'.format(product['name']))
            
            return redirect(url_for('store.store_manager', id=g.user['store_id']))
        else:
            # show error if something went wrong
            flash('Something went wrong. {}'.format(form.errors))

    return render_template('product_update.html', form=form, product=product)

@catalog.route('/product/delete/<string:id>')
def product_delete(id):

    with db.connection.cursor() as cursor:
        # reconnect to heroku clear_db
        db.reconnect()
        # delete product from database
        cursor.execute('DELETE FROM product WHERE product.product_id=%s', (int(id)))
        db.connection.commit()
        
        # success message
        flash('Product deleted')

        return redirect(url_for('store.store_manager', id=g.user['store_id']))
        

ecommerce/main/routes.py
from flask import Blueprint, render_template, session, g, url_for, redirect
from ecommerce.db import Database as db

main = Blueprint('main', __name__)

@main.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@main.route('/')
def index():
    
    with db.connection.cursor() as cursor:
        # reconnect to heroku
        db.reconnect()
        
        # get categories
        cursor.execute('SELECT DISTINCT * FROM category LIMIT 10')
        category_list = cursor.fetchall() 
         
        # get products
        cursor.execute("SELECT * FROM product_view")
        product_list = cursor.fetchall()
 
    return render_template('index.html', product_list=product_list, category_list=category_list)

@main.route('/category/<string:name>')
def filtered_by_category(name):
    
    with db.connection.cursor() as cursor:
        # reconnect to heroku
        db.reconnect()

        cursor.execute('SELECT DISTINCT * FROM category')
        category_list = cursor.fetchall()
        
        cursor.execute('SELECT * FROM product_view WHERE category_name LIKE (%s)', (
                        name))
        product_list = cursor.fetchall()
        
    return render_template('product_filtered_by_category.html', product_list=product_list, category_list=category_list)

ecommerce/users/routes.py
import pymysql
from flask import Blueprint, render_template, session, redirect, url_for, flash, g, request
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
from ecommerce.users.forms import (UserRegistrationForm, UserLoginForm, AddressCreateForm, 
                                   ProfileUpdateForm, AddressUpdateForm, UserPasswordUpdateForm)
from ecommerce.db import Database as db
#from ecommerce import mysql

users = Blueprint('users', __name__)

# authentication decorator
def is_authenticated(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'is_authenticated' in session:
            return f(*args, **kwargs)
        else:
            flash('Unauthised page. Make sure you have the rights to view this page')
            return redirect(url_for('users.user_login'))
    return wrap

@users.before_request
def before_request():
    g.user = None
    if 'user' in session:
        g.user = session['user']

@users.route('/login', methods=['GET', 'POST'])
def user_login():
    '''Controller to authenticate a user and start a session'''
    form = UserLoginForm()
    error = None

    if form.validate_on_submit():
        with db.connection.cursor() as cursor:
            try:
                # retrieve user from the database where the email equals the input value
                cursor.execute('SELECT * FROM user WHERE email LIKE (%s)', (form.email.data))

                # fetch retreived user
                user = cursor.fetchone()
                session.pop('user', None)
                
            except (pymysql.OperationalError):
                # Reconnect first if an operationalError occures and repeat previous steps
                db.reconnect()
                cursor.execute('SELECT * FROM user WHERE email LIKE (%s)', (form.email.data)) 
                
                # fetch retreived user
                user = cursor.fetchone()
                session.pop('user', None)

            if user is None:
                # checks if user exists, if not display error message
                error = 'User doesn\'t exist'

            elif not check_password_hash(user['password'], form.password.data):
                #checks if password matches when user exists, if not displays error message
                error = 'Please insert correct username and password'

            else:
                # start new session with user, redirect to dashboard page
                session['is_authenticated'] = True
                session['user'] = user
                return redirect(url_for('users.account', id=user['user_id']))

            # display if any errors occur
            flash(error)

    return render_template('login.html', form=form)
    
@users.route('/logout')
@is_authenticated
def logout():
    '''Controller to logout users by ending clearing the session'''
    session.pop('user', None)
    session.pop('is_authenticated', False)
    return redirect(url_for('users.user_login'))


@users.route('/register', methods=['POST', 'GET'])
def register():
    '''Controller for registering new users'''
    form = UserRegistrationForm()
 
    if form.validate_on_submit():
        with db.connection.cursor() as cursor:
            db.reconnect()
            # insert new user object into user
            cursor.execute('INSERT INTO user (firstname, lastname, email, password, is_active) VALUES (%s, %s, %s, %s, %s)', (
            form.firstname.data,
            form.lastname.data,
            form.email.data,
            generate_password_hash(form.password1.data),
            True))

            # commit to db
            db.connection.commit()

            # select new registered user
            cursor.execute('SELECT user_id FROM user WHERE email LIKE (%s)', (
                            form.email.data))
            user = cursor.fetchone() 
            session.pop('user', None)
            
            session['is_authenticated'] = True
            session['user'] = user
        
        flash('Awesome! You just created an account and can now login')
        
        # redirect user to address form
        return redirect(url_for('users.register_address', id=user['user_id']))

    else:
        print(form.errors)
        print('Failed to insert new user to db')

    return render_template('register.html', form=form)

@users.route('/register/address/<string:id>', methods=['GET', 'POST'])
@is_authenticated
def register_address(id):
    form = AddressCreateForm()
    
    with db.connection.cursor() as cursor:
        db.reconnect()

        # select cities
        cursor.execute('SELECT * FROM city')
        city_list = cursor.fetchall()
        form.city.choices = [(city['city_id'], city['name']) for city in city_list]

        if form.validate_on_submit():
            cursor.execute("INSERT INTO address (line1, line2, line3, postal_code, city_id) VALUES (%s, %s, %s, %s, %s)", (
                            form.line1.data,
                            form.line2.data,
                            form.line3.data,
                            form.postal_code.data,
                            form.city.data))
            # save address
            db.connection.commit()

            # select address
            cursor.execute("SELECT address_id FROM address WHERE line1=%s", (
                            form.line1.data))
            address = cursor.fetchone()
            
            # insert address
            cursor.execute("UPDATE user SET address_id = %s WHERE user_id = %s", (
                            address['address_id'],
                            id))
            db.connection.commit()

            flash('User has been created. Sign in with your email and password')
            
            return redirect(url_for('users.logout'))
    if form.errors:
        print(form.errors)

    return render_template('register_address.html', form=form)

@users.route('/profile/<string:id>', methods=['GET', 'POST'])
@is_authenticated
def profile(id):
    '''render the user profile details'''
    password_form = UserPasswordUpdateForm()
    address_form =AddressUpdateForm()
    profile_form = ProfileUpdateForm()

    with db.connection.cursor() as cursor:
        # reconnect to heroku mysql db
        db.reconnect()
        
        # get all cities for select form
        cursor.execute('''SELECT city_id, name FROM city''')
        city_list = cursor.fetchall()
        address_form.city.choices = [(city['city_id'], city['name']) for city in city_list]

        # get data from current user
        cursor.execute('SELECT firstname, lastname, email, address_line1, address_line2, address_line3, postal_code, city_id, city_name FROM customer_view WHERE user_id=%s',(
                        id))
        user = cursor.fetchone()

    # Populate user detail fields
    profile_form.email.data = user['email']
    profile_form.firstname.data = user['firstname']
    profile_form.lastname.data = user['lastname']

    address_form.address_line1.data = user['address_line1']
    address_form.address_line2.data = user['address_line2']
    address_form.address_line3.data = user['address_line3']
    address_form.postal_code.data = user['postal_code']
    address_form.city.data = user['city_id'] 

    return render_template('profile.html',user=user, profile_form=profile_form, address_form=address_form, password_form=password_form)

@users.route('/profile/update/<string:id>', methods=['GET','POST'])
@is_authenticated
def profile_update(id):
    '''Controller to update the user's email, name, lastname'''

    profile_form = ProfileUpdateForm()
    address_form = AddressUpdateForm()
    password_form = UserPasswordUpdateForm()
   
    with db.connection.cursor() as cursor:
        # reconnect to heroku
        db.reconnect()

        if profile_form.validate_on_submit():
            cursor.execute('UPDATE customer_view SET firstname=%s, lastname=%s, email=%s WHERE user_id=%s', (
                            request.form['firstname'],
                            request.form['lastname'],
                            request.form['email'],
                            id)) 
            db.connection.commit()
             
            flash('Successfully updated')

            return redirect(url_for('users.profile', id=g.user['user_id']))
       
    return render_template('profile.html', profile_form=profile_form, address_form=address_form, password_form=password_form)

@users.route('/profile/update/password/<string:id>', methods=['POST', 'GET'])
@is_authenticated
def password_update(id):
    '''Controller to handle the password update form'''

    #profile_form = UserUpdateForm()
    #address_form = AddressUpdateForm()
    profile_form = ProfileUpdateForm()
    address_form = AddressUpdateForm()
    password_form = UserPasswordUpdateForm()


    if password_form.validate_on_submit():
        # Update the user password if the user passes the form validation
        with db.connection.cursor() as cursor:
            cursor.execute('''UPDATE user SET password = (%s) WHERE user_id = (%s)''',
                    (generate_password_hash(password_form.new_password1.data),
                    id))
            # save changes to db
            db.connection.commit()


            # show success message and redirect to the same page
            flash('Password has been updated')
            return redirect(url_for('users.profile', id=g.user['user_id']))
    else:
        flash('Something went wrong')
 
    return render_template('profile.html', profile_form=profile_form, address_form=address_form, password_form=password_form)


@users.route('/profile/update/address/<string:id>', methods=['GET', 'POST'])
@is_authenticated
def address_update(id):
    '''Controller to handle address update form'''

    profile_form = ProfileUpdateForm()
    address_form = AddressUpdateForm()
    password_form = UserPasswordUpdateForm()

    with db.connection.cursor() as cursor:

ecommerce/templates/footer.html
<footer class="page-footer">
	<div class="container">

	</div>
	<div class="footer-copyright">
		<div class="container">
			<a href="">Admin</a>
		</div>
	</div>
</footer>

ecommerce/templates/index.html
{% extends 'base.html' %}

{% include 'includes/navbar.html' %}

{% block body %}
<div class="row">
		
	<!-- Categories pagination -->
	<ul class="pagination">
		<li><a href="{{ url_for('main.index') }}">All</a></li>
		{% for c in category_list %}
		<li><a href="{{ url_for('main.filtered_by_category', name=c.category_name) }}">{{ c.category_name }}</a></li>
		{% endfor %}
	</ul>

	<!-- Loop through the product objects and display them -->
	{% if product_list %}
	{% for product in product_list %}
	<div class="col l4 s12">
		<div class="card">
			<div class="card-image">
				<a href="{{ url_for('catalog.product_detail', id=product.product_id) }}">
					<img src="../static/img/product_default.jpg" alt="">
				</a>
				<a href="{{ url_for('cart.cart_items', id=product.product_id ) }}" class="btn-floating halfway-fab waves-effect waves-light green accent-4">
					<i class="material-icons">add</i>
				</a>
			</div>
			<div class="card-content">	
			<small class="grey-text"></small>
			<span class="card-title">{{ product.name }}</span>
				<p class="truncate">{{ product.description }}</p>
			</div>
			<div class="card-action">
				<a href="">$ {{ product.price }}</a>
			</div>
		</div>
	</div>
	{% endfor %}
	{% else %}
		<p class="center-align">Wow, such empty!</p>
	{% endif %}
</div>

{% endblock body %}


{% block footer %}
	{% include 'includes/footer.html' %}
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

<!-- Change body background color to green -->
{% block body_class %}green accent-4{% endblock body_class %}

{% block body %}
<h5 class="center-align white-text">
	<a href="{{ url_for('main.index') }}" class="white-text">
		<i class="material-icons large">keyboard_arrow_left</i>
	</a>
</h5>
<div class="row">
	<div class="col l6 offset-l3 s10 offset-s1">
		<div class="section">
		<div class="card animated bounce">
			<div class="card-content center-align">
				<span class="card-title bounce">Login</span>
				<form action="" method="POST">
					{{ form.csrf_token }}
					<div class="input-field">
						{{ form.email(class="validate") }}
						{{ form.email.label() }}
					</div>
					<div class="input-field">
						{{ form.password(class="validate") }}
						{{ form.password.label() }}
					</div>
					<div class="input-field">
						{{ form.login(class="btn  green accent-4 white-text") }}
					</div>
				</form>
			</div>
			<div class="card-action center-align">
				<p class="">No account yet? <a href="{{ url_for('users.register') }}" class="green-text darken-2">Register</a></p>
			</div>
		</div>
		</div>
	</div>
</div>
</div>
{% endblock body %}

ecommerce/templates/order_confirm.html
{% extends 'base.html' %}

{% block title %}Payment{% endblock %}

{% include 'includes/navbar.html' %}

{% block body %}
<div class="row">
	<div class="col s12">
		<div class="card">
			<div class="card-content">
				<div class="row valign-wrapper">
					<div class="col s7"><span class="card-title">Your order</span></div>
					<div class="col s5"><span class="card-title right-align">Delivery address</span></div>
				</div>
				<div class="row">
					<div class="col s7">
						<table class="responsive-table highlight">
							<thead>
								<tr>
									<th>Item</th>
									<th>Quantity</th>
									<th>Price</th>
									<th></th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								{% for item in session.cart_item %}
								<tr>
									<td>{{ item }}</td>
									<td>{{ session.cart_item[item]['qty'] }}</td>
									<td>{{ session.cart_item[item]['price'] }}</td>
									<th></th>
									<th></th>
								</tr>
								{% endfor %}
							</tbody>
							<thead>
								<tr>
									<th></th>
									<th></th>
									<th> Total Price: {{ total_price }} </th>
								</tr>
							</thead>
						</table>			
					</div>
					<div class="col s5 right-align">
						<p>{{ customer.line1 }}</p>
						<p>{{ customer.line2 }}</p>
						<p>{{ customer.line3 }}</p>
						<p>{{ customer.postal_code }}</p>
						<p>{{ customer.city_name }}, {{ customer.country_name }}</p>
						<h6>Receiver</h6>
						<p class="green-text">{{ customer.firstname }} {{ customer.lastname }}</p>
						<p>{{ customer.email }}</p>
					</div>
				</div>
				<form action="" method="post">
					<h5>Payment method</h5>
					<div class="row valign-wrapper">
						<div class="input-field col s4">
							{{ form.payment_method(class="browser-default") }}
						</div>
						<div class="col s8">
							{{ form.submit(class="btn green accent-4 white-text") }}
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock body %}

ecommerce/templates/product_list.html
{% extends 'base.html' %}

{% block title %}Products{% endblock title %}

{% block body %}
<h4>Products</h4>
<div class="row">
	{% for product in product_list %}
	<div class="col s4">
		<div class="card">
			<div class="card-image">
				<a href="{{ url_for('catalog.product_detail', id=product_id) }}">
					<img src="../static/img/product_default.jpg" alt="">
				</a>
			</div>
			<div class="card-content">
				<span class="card-title">{{ product.name }}</span>
				<p class="truncate">{{ product.description }}</p>
			</div>
			<div class="card-action">
				<a href="">$ {{ product.price }}</a>
				<a href="">Stock {{ product.stock }}</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock body %}

ecommerce/templates/profile.html
{% extends 'base.html' %}

{% include 'includes/navbar.html' %}

{% block body %}
<div class="row">
	<!-- Profile overview -->
	{% include 'includes/profile_detail.html' %}

	<!-- user update form -->
	<div class="col s12">
		<div class="card">
			<div class="card-content">
				<span class="card-title valign-wrapper">
					Update profile
				</span>
				<form action="{{ url_for('users.profile_update', id=g.user.user_id) }}" method="POST">
					{{ profile_form.csrf_token() }}
					<div class="input-field">
						{{ profile_form.email(class="validate") }}
						{{ profile_form.email.label() }}
					</div>
					<div class="input-field">
						{{ profile_form.firstname(class="validate") }}
						{{ profile_form.firstname.label() }}
					</div>
					<div class="input-field">
						{{ profile_form.lastname(class="validate") }}
						{{ profile_form.lastname.label() }}
					</div>	
					<div class="input-field">
						{{ profile_form.submit(class="btn green accent-4 white-text")}}
					</div>
				</form>
			</div>
		</div>
	</div>
		
	<!-- Update Address FORM -->
	<div class="col s12">
		<div class="card">
			<div class="card-content">
				<span class="card-title valign-wrapper">Update address</span>
				<form action="{{ url_for('users.address_update', id=g.user.user_id) }}" method="POST">
					{{ address_form.csrf_token() }}
					<div class="input-field">
						{{ address_form.address_line1(class='validate') }}
						{{ address_form.address_line1.label() }}
					</div>
					<div class="input-field">
						{{ address_form.address_line2(class="") }}
						{{ address_form.address_line2.label() }}
						<span class="helper-text">Optional</span>
					</div>
					<div class="input-field">
						{{ address_form.address_line3(class="") }}
						{{ address_form.address_line3.label() }}
						<span class="helper-text">Optional</span>
					</div>
					<div class="input-field">
						{{ address_form.postal_code(class="validate") }}
						{{ address_form.postal_code.label() }}
					</div>
					<div class="input-field">
						{{ address_form.city(class="browser-default") }}
					</div>
					<div class="input-field">
						{{ address_form.submit(class="btn green accent-4 white-text") }}
					</div>
				</form>
			</div>
		</div>
	</div>

	<!-- Update password FORM -->
	<div class="col s12">
		<div class="card">
			<div class="card-content">
				<span class="card-title valign-wrapper">

					Update password
				</span>
				<form action="{{ url_for('users.password_update', id=g.user.user_id) }}" method="post">
					{{ password_form.csrf_token() }}
					<div class="input-field">
						{{ password_form.new_password1(class='validate') }}
						{{ password_form.new_password1.label() }}
					</div>
					<div class="input-field">
						{{ password_form.new_password2(class="validate") }}
						{{ password_form.new_password2.label() }}
					</div>
					<div class="input-field">
						{{ password_form.submit(class="btn green accent-4 white-text") }}
					</div>
				</form>
			</div>
		</div>
	</div>

</div>
{% endblock body %}

ecommerce/templates/register.html
{% extends 'base.html' %}

{% block title %}Register user{% endblock %}

{% block body_class %}green accent-4{% endblock body_class %}

{% block body %}
<h4 class="center-align">
	<a href="{{ url_for('main.index') }}" class="white-text">
		<i class="material-icons medium">keyboard_arrow_left</i>
	</a>
</h4>
<div class="row">
	<div class="card col l8 offset-l2 s12 animated bounce">
		<div class="card-content">
			<span class="card-title center-align">Register now</span>
			<form action="" method="post" class="">
				{{ form.hidden_tag() }}
				<!-- firstname & lastname input fields -->

				<div class="row">
					<div class="input-field">
						{{ form.firstname(class="validate")}}
						{{ form.firstname.label() }}
					</div>

					<div class="input-field">
						{{ form.lastname(class="validate") }}
						{{ form.lastname.label() }}
					</div>

					<!-- Email input -->
					<div class="input-field">
						{% if form.email.errors %}
							{{ form.email(class='validate') }}
							{% for error in form.email.errors %}
								<span class="helper-text red-text">{{ error }}</span>
							{% endfor %}
						{% else %}
							{{ form.email(class="validate") }}
						{% endif %}
						{{ form.email.label() }}
					</div>

					<!-- Password input -->
					<div class="input-field">
						{{ form.password1(class="validate") }}
						{{ form.password1.label() }}
					</div>
					<!-- Confirm password input -->
					<div class="input-field">
						{% if form.password2.errors %}
							{{ form.password2(class="validate") }}
							{% for error in form.password2.errors %}
								<span class="helper-text red-text">{{ error }}</span>
							{% endfor %}
						{% else %}
							{{ form.password2(class="validate") }}
						{% endif %}
						{{ form.password2.label() }}
					</div>
					<div class="input-field">
						{{ form.submit(class="btn green accent-4 right") }}
					</div>
			</form>
		</div>
		<div class="card-action center-align">
			Already an account? <a href="{{ url_for('users.user_login') }}" class="green-text darken-2">Login</a>
		</div>
	</div>
</div>
{% endblock body %}

ecommerce/templates/store_detail.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% include 'includes/navbar.html' %}

{% block body %}
<div class="row">
	<!-- Store Details -->
	<div class="col s12">
		<div class="card-panel">
			<div class="row valign-wrapper">
				<div class="col s3">
				</div>
				<div class="col s9">
					<h5 class="green-text">{{ owner.store_name }}</h5>
					<small class="grey-text">
						owner {{ owner.firstname }} {{ owner.lastname }}
					</small>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Products from this store -->
<div class="row">
	{% for p in product_list %}
	<div class="col s6 l4">
		<div class="card">
			<div class="card-content">
				<div class="card-image">
					<a href="{{ url_for('catalog.product_detail', id=p.product_id) }}">
						<img src="../static/img/product_default.jpg" alt="">
					</a>
					<a href="{{ url_for('cart.cart_items', id=p.product_id ) }}" class="btn-floating halfway-fab waves-effect waves-light green accent-4">
						<i class="material-icons">add</i>
					</a>
				</div>
				<span class="card-title">{{ p.name }}</span>
				<small class="grey-text"></small>
				<h6 class="orange-text">$ {{ p.price }}</h6>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock body %}

ecommerce/templates/store_manager.html
{% extends 'base.html' %}

{% block title %}Store Manager{% endblock title %}

{% include 'includes/store_navbar.html' %}

{% block body %}
<!-- Show the owners Products -->
<div class="card">
	<div class="card-content">
		<span class="card-title">My Products</span>
		{% if product_list %}
		<table class="highlight responsive-table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Price</th>
					<th>Category</th>
					<th>Added on</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for product in product_list %}
				<tr>
					<td>
						<a href="{{ url_for('catalog.product_detail', id=product.product_id) }}" class="green-text">
							{{ product.name }}
						</a>
					</td>
					<td>$ {{ '%0.2f'|format(product.price|float) }}</td>
					
					<td>{{ product.category_name }}</td>
					<td>{{ product.added_on.strftime('%d %b %Y - %H:%M') }}</td>
					<td>
						<a href="{{ url_for('catalog.product_delete', id=product.product_id) }}">
							<i class="tiny material-icons red-text">clear</i>
						</a>
					</td>
					<td>
						<a href="{{ url_for('catalog.product_update', id=product.product_id) }}">
							<i class="tiny material-icons">edit_mode</i>
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<p>You don't have any products to sell yet. Start adding them first</p>
		{% endif %}
	</div>
</div>
{% endblock body %}

ecommerce/templates/users.html
{% extends 'base.html' %}

{% block body %}

{% endblock %}